import Quiz from '../models/Quiz.js';
import logger from '../utils/prettyLogger.js';
import Skill from '../models/Skill.js';
import Certificate from '../models/Certificate.js';
import QuizAttempt from '../models/QuizAttempt.js';

// Generate quiz for specific level
export const generateQuizForLevel = async (req, res) => {
  try {
    const { level } = req.params;
    const adminId = req.user.id;

    if (isNaN(level) || level < 0) {
      return res.status(400).json({
        success: false,
        message: 'Level must be a valid number (0 or higher)'
      });
    }

    const quiz = await generateLevelQuiz(parseInt(level), adminId);

    res.status(200).json({
      success: true,
      message: `Quiz generated successfully for Level ${level}`,
      data: quiz
    });

  } catch (error) {
    logger.errorWithStack('Generate quiz for level error:', error, error, 'CONTROLLER');
    res.status(500).json({
      success: false,
      message: 'Error generating quiz',
      error: error.message
    });
  }
};

// Generate Quizzes for all levels
export const generateAllQuizzes = async (req, res) => {
  try {
    const adminId = req.user.id;

    const quizzes = await generateAllLevelQuizzes(adminId);

    res.status(200).json({
      success: true,
      message: `Generated ${quizzes.length} Quizzes successfully`,
      data: quizzes
    });

  } catch (error) {
    logger.errorWithStack('Generate all Quizzes error:', error, error, 'CONTROLLER');
    res.status(500).json({
      success: false,
      message: 'Error generating Quizzes',
      error: error.message
    });
  }
};

// Get quiz for specific level
export const getQuizForLevel = async (req, res) => {
  try {
    const { level } = req.params;

    if (isNaN(level) || level < 0) {
      return res.status(400).json({
        success: false,
        message: 'Level must be a valid number (0 or higher)'
      });
    }

    const quiz = await getLevelQuiz(parseInt(level));

    if (!quiz) {
      return res.status(404).json({
        success: false,
        message: `No quiz found for Level ${level}`
      });
    }

    res.status(200).json({
      success: true,
      data: quiz
    });

  } catch (error) {
    logger.errorWithStack('Get quiz for level error:', error, error, 'CONTROLLER');
    res.status(500).json({
      success: false,
      message: 'Error getting quiz',
      error: error.message
    });
  }
};

// Get all auto-generated Quizzes
export const getAutoGeneratedQuizzes = async (req, res) => {
  try {
    const quizzes = await Quiz.find({
      tags: { $in: ['auto-generated'] },
      isActive: true
    })
    .populate('createdBy', 'name email')
    .sort({ createdAt: -1 });

    res.status(200).json({
      success: true,
      data: quizzes
    });

  } catch (error) {
    logger.errorWithStack('Get auto-generated Quizzes error:', error, error, 'CONTROLLER');
    res.status(500).json({
      success: false,
      message: 'Error getting auto-generated Quizzes',
      error: error.message
    });
  }
};

// Delete auto-generated quiz
export const deleteAutoGeneratedQuiz = async (req, res) => {
  try {
    const { quizId } = req.params;
    const adminId = req.user.id;

    const quiz = await Quiz.findOne({
      _id: quizId,
      tags: { $in: ['auto-generated'] }
    });

    if (!quiz) {
      return res.status(404).json({
        success: false,
        message: 'Auto-generated quiz not found'
      });
    }

    await Quiz.findByIdAndDelete(quizId);

    res.status(200).json({
      success: true,
      message: 'Auto-generated quiz deleted successfully'
    });

  } catch (error) {
    logger.errorWithStack('Delete auto-generated quiz error:', error, error, 'CONTROLLER');
    res.status(500).json({
      success: false,
      message: 'Error deleting quiz',
      error: error.message
    });
  }
};

// Helper function to generate quiz for a specific level
const generateLevelQuiz = async (level, adminId) => {
  try {
    // Always delete existing quiz for this level and regenerate fresh
    // so new lessons added to the level are always picked up
    const existingQuiz = await Quiz.findOne({
      tags: { $all: [`level-${level}`, 'auto-generated'] },
      isActive: true
    });

    if (existingQuiz) {
      logger.info(`Deleting existing quiz for Level ${level} to regenerate fresh`, null, 'CONTROLLER');
      await Quiz.findByIdAndDelete(existingQuiz._id);

      // Also delete all quiz attempts for the old quiz so users must re-earn progression
      await QuizAttempt.deleteMany({ quizId: existingQuiz._id });

      // Also delete stale level_mastery certificates for this level so they must be re-earned
      const certTitleVariants = [
        `Level ${level} Mastery`,
        level === 0 ? 'Level 0 Basics' : null,
        level === 2 ? 'Level 2 Intermediate' : null,
        level === 3 ? 'Level 3 Advanced' : null,
      ].filter(Boolean);
      const deletedCerts = await Certificate.deleteMany({
        title: { $in: certTitleVariants },
        type: 'level_mastery'
      });
      if (deletedCerts.deletedCount > 0) {
        logger.info(`🗑️ Deleted ${deletedCerts.deletedCount} stale certificate(s) for Level ${level} — must be re-earned`, null, 'CONTROLLER');
      }
    }

    // Get all skills for the specified level
    const skills = await Skill.find({ 
      level: level, 
      isActive: true 
    }).sort({ order: 1 });

    if (skills.length === 0) {
      throw new Error(`No skills found for Level ${level}`);
    }

    // Extract ALL flashcards from ALL lessons/skills at this level (mix them all together)
    const allFlashcards = [];
    skills.forEach(skill => {
      if (skill.flashcards && skill.flashcards.length > 0) {
        skill.flashcards.forEach(card => {
          allFlashcards.push({
            ...card.toObject(),
            moduleTitle: skill.title,
            moduleCategory: skill.category
          });
        });
      }
    });

    if (allFlashcards.length === 0) {
      throw new Error(`No flashcards found for Level ${level}`);
    }

    // Shuffle the full pool and pick up to 10 unique cards
    const shuffled = [...allFlashcards].sort(() => 0.5 - Math.random());
    const selectedCards = shuffled.slice(0, Math.min(10, shuffled.length));

    // Build a pool of real word names to use as wrong-answer distractors
    // (all words from the full flashcard pool, deduplicated)
    const allWords = allFlashcards
      .map(c => c.word)
      .filter(Boolean)
      .filter((v, i, a) => a.indexOf(v) === i); // unique values only

    const questions = [];
    const usedWords = new Set();

    selectedCards.forEach(card => {
      if (!card.word || usedWords.has(card.word.toLowerCase())) {
        return;
      }

      usedWords.add(card.word.toLowerCase());

      const correctAnswer = card.word; // Correct answer is always the SIGN NAME/WORD

      // Use real words from OTHER flashcards as distractors (smart MCQ)
      const distractorPool = allWords.filter(w => w.toLowerCase() !== correctAnswer.toLowerCase());

      // Shuffle distractors and pick 3
      const shuffledDistractors = [...distractorPool].sort(() => 0.5 - Math.random());
      const selectedWrong = shuffledDistractors.slice(0, 3);

      // If not enough real distractors, pad with generic sign names
      const fallbacks = ['Namaste', 'Thank You', 'Please', 'Sorry', 'Yes', 'No', 'Help', 'Water'];
      while (selectedWrong.length < 3) {
        const fb = fallbacks.shift();
        if (fb && fb.toLowerCase() !== correctAnswer.toLowerCase() && !selectedWrong.includes(fb)) {
          selectedWrong.push(fb);
        }
      }

      // Build options array (word names) and shuffle
      const options = [
        { text: correctAnswer, isCorrect: true },
        ...selectedWrong.map(text => ({ text, isCorrect: false }))
      ].sort(() => 0.5 - Math.random());

      // Decide question text based on available media
      const hasImage = card.imagePath || (card.additionalImages && card.additionalImages.length > 0);
      const hasVideo = card.videoPath || (card.additionalVideos && card.additionalVideos.length > 0);

      // SIGN RECOGNITION FORMAT:
      // If media is available → show the sign visually, ask "which sign is this?"
      // If no media → text fallback asking about the sign
      const questionText = hasImage || hasVideo
        ? `Which sign is being shown in the image?`
        : `What sign represents "${card.meaning}"?`;

      const mediaUrl = card.imagePath || (card.additionalImages && card.additionalImages[0]) || null;
      const videoUrl = card.videoPath || (card.additionalVideos && card.additionalVideos[0]) || null;

      questions.push({
        question: questionText,
        type: 'multiple-choice',
        options,
        correctAnswer,
        explanation: `The sign shown is "${correctAnswer}" (${card.meaning}). It comes from the "${card.moduleTitle}" lesson.`,
        difficulty: level <= 1 ? 'Beginner' : level <= 3 ? 'Intermediate' : 'Advanced',
        points: 10,
        mediaUrl,
        videoUrl
      });
    });

    if (questions.length === 0) {
      throw new Error(`No valid questions could be generated for Level ${level}`);
    }

    // Time limit: 2 minutes per question (minimum 10)
    const timeLimit = Math.max(10, questions.length * 2);

    // Create the quiz — must set quizType:'mastery' and level so unlock logic can find it
    const quiz = new Quiz({
      title: `Level ${level} Mastery Quiz`,
      description: `Auto-generated quiz for Level ${level} — mixing questions from ${skills.length} lesson(s). Pass to unlock the next level!`,
      category: 'advanced',
      quizType: 'mastery',        // ← required for checkLevelQuizPassed()
      level: level,               // ← required for checkLevelQuizPassed() — supports level 0
      difficulty: level <= 1 ? 'Beginner' : level <= 3 ? 'Intermediate' : 'Advanced',
      timeLimit,
      passingScore: 70,
      maxAttempts: 3,
      tags: ['auto-generated', `level-${level}`],
      questions,
      createdBy: adminId,
      isActive: true
    });

    await quiz.save();
    logger.info(`Generated Level ${level} Mastery Quiz with ${questions.length} questions from ${skills.length} lessons`, null, 'CONTROLLER');
    return quiz;

  } catch (error) {
    logger.errorWithStack('Error generating level quiz:', error, error, 'CONTROLLER');
    throw error;
  }
};

// Helper function to generate Quizzes for all levels
const generateAllLevelQuizzes = async (adminId) => {
  try {
    const quizzes = [];
    
    // Get all unique levels
    const levels = await Skill.distinct('level', { isActive: true });
    
    for (const level of levels) {
      try {
        const quiz = await generateLevelQuiz(level, adminId);
        quizzes.push(quiz);
      } catch (error) {
        logger.errorWithStack(`Error generating quiz for Level ${level}:`, error, error, 'CONTROLLER');
        // Continue with other levels even if one fails
      }
    }
    
    return quizzes;
  } catch (error) {
    logger.errorWithStack('Error generating all level Quizzes:', error, error, 'CONTROLLER');
    throw error;
  }
};

// Helper function to get quiz for a specific level
const getLevelQuiz = async (level) => {
  try {
    const quiz = await Quiz.findOne({
      tags: { $in: [`level-${level}`] },
      isActive: true
    }).populate('createdBy', 'name email');
    
    return quiz;
  } catch (error) {
    logger.errorWithStack('Error getting level quiz:', error, error, 'CONTROLLER');
    throw error;
  }
};
