import Quiz from '../models/Quiz.js';
import logger from '../utils/prettyLogger.js';
import Skill from '../models/Skill.js';

// Generate quiz for specific level
export const generateQuizForLevel = async (req, res) => {
  try {
    const { level } = req.params;
    const adminId = req.user.id;

    if (isNaN(level) || level < 0) {
      return res.status(400).json({
        success: false,
        message: 'Level must be a valid number (0 or higher)'
      });
    }

    const quiz = await generateLevelQuiz(parseInt(level), adminId);

    res.status(200).json({
      success: true,
      message: `Quiz generated successfully for Level ${level}`,
      data: quiz
    });

  } catch (error) {
    logger.errorWithStack('Generate quiz for level error:', error, error, 'CONTROLLER');
    res.status(500).json({
      success: false,
      message: 'Error generating quiz',
      error: error.message
    });
  }
};

// Generate quizzes for all levels
export const generateAllQuizzes = async (req, res) => {
  try {
    const adminId = req.user.id;

    const quizzes = await generateAllLevelQuizzes(adminId);

    res.status(200).json({
      success: true,
      message: `Generated ${quizzes.length} quizzes successfully`,
      data: quizzes
    });

  } catch (error) {
    logger.errorWithStack('Generate all quizzes error:', error, error, 'CONTROLLER');
    res.status(500).json({
      success: false,
      message: 'Error generating quizzes',
      error: error.message
    });
  }
};

// Get quiz for specific level
export const getQuizForLevel = async (req, res) => {
  try {
    const { level } = req.params;

    if (isNaN(level) || level < 0) {
      return res.status(400).json({
        success: false,
        message: 'Level must be a valid number (0 or higher)'
      });
    }

    const quiz = await getLevelQuiz(parseInt(level));

    if (!quiz) {
      return res.status(404).json({
        success: false,
        message: `No quiz found for Level ${level}`
      });
    }

    res.status(200).json({
      success: true,
      data: quiz
    });

  } catch (error) {
    logger.errorWithStack('Get quiz for level error:', error, error, 'CONTROLLER');
    res.status(500).json({
      success: false,
      message: 'Error getting quiz',
      error: error.message
    });
  }
};

// Get all auto-generated quizzes
export const getAutoGeneratedQuizzes = async (req, res) => {
  try {
    const quizzes = await Quiz.find({
      tags: { $in: ['auto-generated'] },
      isActive: true
    })
    .populate('createdBy', 'name email')
    .sort({ createdAt: -1 });

    res.status(200).json({
      success: true,
      data: quizzes
    });

  } catch (error) {
    logger.errorWithStack('Get auto-generated quizzes error:', error, error, 'CONTROLLER');
    res.status(500).json({
      success: false,
      message: 'Error getting auto-generated quizzes',
      error: error.message
    });
  }
};

// Delete auto-generated quiz
export const deleteAutoGeneratedQuiz = async (req, res) => {
  try {
    const { quizId } = req.params;
    const adminId = req.user.id;

    const quiz = await Quiz.findOne({
      _id: quizId,
      createdBy: adminId,
      tags: { $in: ['auto-generated'] }
    });

    if (!quiz) {
      return res.status(404).json({
        success: false,
        message: 'Auto-generated quiz not found or not authorized to delete'
      });
    }

    await Quiz.findByIdAndDelete(quizId);

    res.status(200).json({
      success: true,
      message: 'Auto-generated quiz deleted successfully'
    });

  } catch (error) {
    logger.errorWithStack('Delete auto-generated quiz error:', error, error, 'CONTROLLER');
    res.status(500).json({
      success: false,
      message: 'Error deleting quiz',
      error: error.message
    });
  }
};

// Helper function to generate quiz for a specific level
const generateLevelQuiz = async (level, adminId) => {
  try {
    // Check if quiz already exists for this level
    const existingQuiz = await Quiz.findOne({
      tags: { $in: [`level-${level}`] },
      isActive: true
    });

    if (existingQuiz) {
      logger.info('Quiz already exists for Level ${level}, returning existing quiz', null, 'CONTROLLER');
      return existingQuiz;
    }

    // Get all skills for the specified level
    const skills = await Skill.find({ 
      level: level, 
      isActive: true 
    }).sort({ order: 1 });

    if (skills.length === 0) {
      throw new Error(`No skills found for Level ${level}`);
    }

    // Extract flashcards from all skills
    const allFlashcards = [];
    skills.forEach(skill => {
      if (skill.flashcards && skill.flashcards.length > 0) {
        skill.flashcards.forEach(card => {
          allFlashcards.push({
            ...card.toObject(),
            moduleTitle: skill.title,
            moduleCategory: skill.category
          });
        });
      }
    });

    if (allFlashcards.length === 0) {
      throw new Error(`No flashcards found for Level ${level}`);
    }

    // Generate quiz questions from flashcards
    const questions = [];
    const usedWords = new Set();
    
    // Take up to 10 random flashcards to create questions
    const shuffled = allFlashcards.sort(() => 0.5 - Math.random());
    const selectedCards = shuffled.slice(0, Math.min(10, shuffled.length));

    selectedCards.forEach(card => {
      if (!card.word || usedWords.has(card.word.toLowerCase())) {
        return;
      }
      
      usedWords.add(card.word.toLowerCase());
      
      // Create multiple choice options with realistic alternatives
      const correctAnswer = card.meaning || 'No meaning provided';
      const wrongOptions = [
        'I don\'t know',
        'Something else',
        'Not sure',
        'Maybe',
        'Possibly',
        'Could be',
        'Uncertain'
      ];
      
      // Shuffle and select 3 wrong options
      const shuffledWrong = wrongOptions.sort(() => 0.5 - Math.random());
      const selectedWrong = shuffledWrong.slice(0, 3);
      
      // Create options array with correct answer and wrong options
      const options = [
        { text: correctAnswer, isCorrect: true },
        ...selectedWrong.map(text => ({ text, isCorrect: false }))
      ];
      
      // Shuffle the options so correct answer isn't always first
      const shuffledOptions = options.sort(() => 0.5 - Math.random());
      
      // Create a more engaging question format
      const hasImage = card.imagePath || (card.additionalImages && card.additionalImages.length > 0);
      const hasVideo = card.videoPath || (card.additionalVideos && card.additionalVideos.length > 0);
      
      const questionText = hasImage || hasVideo
        ? `Look at the sign image/video and select the correct meaning:`
        : `What does the sign "${card.word}" mean?`;
      
      // Get the first available image or video
      const mediaUrl = card.imagePath || (card.additionalImages && card.additionalImages[0]) || null;
      const videoUrl = card.videoPath || (card.additionalVideos && card.additionalVideos[0]) || null;
      
      const question = {
        question: questionText,
        type: 'multiple-choice',
        options: shuffledOptions,
        correctAnswer: correctAnswer,
        explanation: `The sign "${card.word}" means "${correctAnswer}".`,
        difficulty: 'Beginner',
        points: 10,
        mediaUrl: mediaUrl,
        videoUrl: videoUrl
      };
      
      questions.push(question);
    });

    if (questions.length === 0) {
      throw new Error(`No valid questions could be generated for Level ${level}`);
    }

    // Create the quiz
    const quiz = new Quiz({
      title: `Level ${level} Mastery Quiz`,
      description: `Auto-generated quiz for Level ${level} based on learning modules`,
      category: 'advanced',
      difficulty: 'Beginner',
      timeLimit: 15,
      passingScore: 70,
      maxAttempts: 3,
      tags: ['auto-generated', `level-${level}`],
      questions: questions,
      createdBy: adminId,
      isActive: true
    });

    await quiz.save();
    return quiz;

  } catch (error) {
    logger.errorWithStack('Error generating level quiz:', error, error, 'CONTROLLER');
    throw error;
  }
};

// Helper function to generate quizzes for all levels
const generateAllLevelQuizzes = async (adminId) => {
  try {
    const quizzes = [];
    
    // Get all unique levels
    const levels = await Skill.distinct('level', { isActive: true });
    
    for (const level of levels) {
      try {
        const quiz = await generateLevelQuiz(level, adminId);
        quizzes.push(quiz);
      } catch (error) {
        logger.errorWithStack(`Error generating quiz for Level ${level}:`, error, error, 'CONTROLLER');
        // Continue with other levels even if one fails
      }
    }
    
    return quizzes;
  } catch (error) {
    logger.errorWithStack('Error generating all level quizzes:', error, error, 'CONTROLLER');
    throw error;
  }
};

// Helper function to get quiz for a specific level
const getLevelQuiz = async (level) => {
  try {
    const quiz = await Quiz.findOne({
      tags: { $in: [`level-${level}`] },
      isActive: true
    }).populate('createdBy', 'name email');
    
    return quiz;
  } catch (error) {
    logger.errorWithStack('Error getting level quiz:', error, error, 'CONTROLLER');
    throw error;
  }
};