import express from 'express';
import { protect, authorize } from '../middleware/auth.js';
import {
  generateQuizForLevel,
  generateAllQuizzes,
  getQuizForLevel,
  getAutoGeneratedQuizzes,
  deleteAutoGeneratedQuiz
} from '../controllers/quizGeneratorController.js';

const router = express.Router();

// All routes require authentication and admin/super_admin role
router.use(protect);
router.use(authorize('admin', 'super_admin'));

// Quiz generation routes
router.post('/generate/level/:level', generateQuizForLevel);
router.post('/generate/all', generateAllQuizzes);
router.get('/level/:level', getQuizForLevel);
router.get('/auto-generated', getAutoGeneratedQuizzes);
router.delete('/auto-generated/:quizId', deleteAutoGeneratedQuiz);

export default router;