import { useState, useEffect } from 'react';
import { useTheme } from '../hooks/useTheme';
import { useAuth } from '../context/AuthContextConstants';
import { API_BASE_URL } from '../constants/api';
import {
  SparklesIcon,
  AcademicCapIcon,
  CheckCircleIcon,
  XCircleIcon,
  TrashIcon,
  PlayIcon,
  ClockIcon,
  StarIcon,
  ArrowPathIcon
} from '@heroicons/react/24/outline';

export default function QuizGenerator() {
  const { darkMode } = useTheme();
  const { token } = useAuth();
  
  // State management
  const [autoGeneratedQuizzes, setAutoGeneratedQuizzes] = useState([]);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);
  const [success, setSuccess] = useState('');
  const [error, setError] = useState('');

  // Theme variables - Transparent dark theme
  const border = darkMode ? 'border-white/20' : 'border-gray-300';
  const cardBg = darkMode ? 'bg-white/5 backdrop-blur-sm' : 'bg-gray-50';
  const inputBg = darkMode ? 'bg-white/10 backdrop-blur-sm' : 'bg-white';

  // Fetch auto-generated quizzes
  const fetchAutoGeneratedQuizzes = async () => {
    try {
      setLoading(true);
      const response = await fetch(`${API_BASE_URL}/api/admin/quiz-generator/auto-generated`, {
        headers: {
          'Authorization': `Bearer ${token}`
        }
      });

      if (response.ok) {
        const data = await response.json();
        // Filter out duplicate quizzes based on _id
        const uniqueQuizzes = (data.data || []).filter((quiz, index, self) => 
          index === self.findIndex(q => q._id === quiz._id)
        );
        setAutoGeneratedQuizzes(uniqueQuizzes);
      } else {
        throw new Error('Failed to fetch auto-generated quizzes');
      }
    } catch (error) {
      console.error('Error fetching auto-generated quizzes:', error);
      setError('Failed to load auto-generated quizzes');
    } finally {
      setLoading(false);
    }
  };

  // Generate quiz for specific level
  const generateQuizForLevel = async (level) => {
    try {
      setGenerating(true);
      setError('');
      
      const response = await fetch(`${API_BASE_URL}/api/admin/quiz-generator/generate/level/${level}`, {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${token}`
        }
      });

      if (response.ok) {
        const data = await response.json();
        setSuccess(`Quiz generated successfully for Level ${level}`);
        fetchAutoGeneratedQuizzes(); // Refresh the list
        setTimeout(() => setSuccess(''), 3000);
      } else {
        const errorData = await response.json();
        throw new Error(errorData.message || 'Failed to generate quiz');
      }
    } catch (error) {
      console.error('Error generating quiz:', error);
      setError(`Failed to generate quiz for Level ${level}: ${error.message}`);
      setTimeout(() => setError(''), 5000);
    } finally {
      setGenerating(false);
    }
  };

  // Generate quizzes for all levels
  const generateAllQuizzes = async () => {
    try {
      setGenerating(true);
      setError('');
      
      const response = await fetch(`${API_BASE_URL}/api/admin/quiz-generator/generate/all`, {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${token}`
        }
      });

      if (response.ok) {
        const data = await response.json();
        setSuccess(`Generated ${data.data?.length || 0} quizzes successfully`);
        fetchAutoGeneratedQuizzes(); // Refresh the list
        setTimeout(() => setSuccess(''), 3000);
      } else {
        const errorData = await response.json();
        throw new Error(errorData.message || 'Failed to generate quizzes');
      }
    } catch (error) {
      console.error('Error generating all quizzes:', error);
      setError(`Failed to generate quizzes: ${error.message}`);
      setTimeout(() => setError(''), 5000);
    } finally {
      setGenerating(false);
    }
  };

  // Delete auto-generated quiz
  const deleteQuiz = async (quizId) => {
    try {
      const response = await fetch(`${API_BASE_URL}/api/admin/quiz-generator/auto-generated/${quizId}`, {
        method: 'DELETE',
        headers: {
          'Authorization': `Bearer ${token}`
        }
      });

      if (response.ok) {
        setSuccess('Quiz deleted successfully');
        fetchAutoGeneratedQuizzes(); // Refresh the list
        setTimeout(() => setSuccess(''), 3000);
      } else {
        const errorData = await response.json();
        throw new Error(errorData.message || 'Failed to delete quiz');
      }
    } catch (error) {
      console.error('Error deleting quiz:', error);
      setError(`Failed to delete quiz: ${error.message}`);
      setTimeout(() => setError(''), 5000);
    }
  };

  useEffect(() => {
    fetchAutoGeneratedQuizzes();
  }, []);

  if (loading) {
    return (
      <div className={`min-h-screen ${darkMode ? 'bg-[#1A1A1A]' : 'bg-gray-50'} p-6`}>
        <div className="animate-pulse">
          <div className="h-8 bg-gray-300 rounded w-1/4 mb-4"></div>
          <div className="space-y-3">
            <div className="h-4 bg-gray-300 rounded"></div>
            <div className="h-4 bg-gray-300 rounded w-5/6"></div>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className={`min-h-screen ${darkMode ? 'bg-[#1A1A1A]' : 'bg-gray-50'} p-6`}>
      <div className="space-y-6">
        {/* Header */}
        <div className={`flex items-center justify-between p-6 rounded-2xl ${cardBg} border ${border}`}>
          <div>
            <h2 className="text-2xl font-bold text-white">Auto Quiz Generator</h2>
            <p className="text-white/70">Generate quizzes automatically from Level 0 modules</p>
          </div>
          <div className="flex items-center space-x-3">
            <button
              onClick={generateAllQuizzes}
              disabled={generating}
              className="inline-flex items-center px-4 py-2 bg-purple-500 text-white rounded-2xl hover:bg-purple-600 disabled:bg-gray-600 disabled:cursor-not-allowed transition-colors"
            >
              {generating ? (
                <ArrowPathIcon className="w-5 h-5 mr-2 animate-spin" />
              ) : (
                <SparklesIcon className="w-5 h-5 mr-2" />
              )}
              Generate All Quizzes
            </button>
          </div>
        </div>

        {/* Success/Error Messages */}
        {success && (
          <div className="p-4 bg-green-100 border border-green-400 text-green-700 rounded-lg dark:bg-green-900 dark:border-green-600 dark:text-green-200">
            {success}
          </div>
        )}
        {error && (
          <div className="p-4 bg-red-100 border border-red-400 text-red-700 rounded-lg dark:bg-red-900 dark:border-red-600 dark:text-red-200">
            {error}
          </div>
        )}

        {/* Quick Generate Buttons */}
        <div className={`p-6 rounded-2xl ${cardBg} border ${border}`}>
          <h3 className="text-lg font-semibold text-white mb-4">Quick Generate</h3>
          <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
            {[0, 1, 2, 3].map(level => (
              <button
                key={level}
                onClick={() => generateQuizForLevel(level)}
                disabled={generating}
                className="flex flex-col items-center p-4 bg-white/10 rounded-2xl border border-white/20 hover:bg-white/20 transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
              >
                <AcademicCapIcon className="w-8 h-8 text-white mb-2" />
                <span className="text-white font-medium">Level {level}</span>
                <span className="text-white/60 text-sm">Quiz</span>
              </button>
            ))}
          </div>
        </div>

        {/* Auto-Generated Quizzes */}
        <div className={`p-6 rounded-2xl ${cardBg} border ${border}`}>
          <h3 className="text-lg font-semibold text-white mb-4">Auto-Generated Quizzes</h3>
          
          {autoGeneratedQuizzes.length === 0 ? (
            <div className="text-center py-8">
              <SparklesIcon className="w-16 h-16 text-white/60 mx-auto mb-4" />
              <h4 className="text-lg font-medium text-white mb-2">No auto-generated quizzes yet</h4>
              <p className="text-white/70 mb-4">Generate quizzes to test user knowledge at each level</p>
              <button
                onClick={generateAllQuizzes}
                disabled={generating}
                className="inline-flex items-center px-6 py-3 bg-purple-500 text-white rounded-2xl hover:bg-purple-600 disabled:bg-gray-600 disabled:cursor-not-allowed transition-colors"
              >
                <SparklesIcon className="w-5 h-5 mr-2" />
                Generate All Quizzes
              </button>
            </div>
          ) : (
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
              {autoGeneratedQuizzes.map((quiz, index) => (
                <div key={`quiz-generator-${quiz._id}-${index}`} className="p-6 bg-white/10 rounded-2xl border border-white/20 backdrop-blur-sm">
                  <div className="flex items-start justify-between mb-4">
                    <div className="flex items-center space-x-3">
                      <div className="p-3 bg-purple-500 rounded-full">
                        <AcademicCapIcon className="w-6 h-6 text-white" />
                      </div>
                      <div>
                        <h4 className="text-lg font-semibold text-white">{quiz.title}</h4>
                        <p className="text-white/60 text-sm">{quiz.description}</p>
                      </div>
                    </div>
                    <button
                      onClick={() => deleteQuiz(quiz._id)}
                      className="p-2 text-red-400 hover:bg-red-500/20 rounded-lg transition-colors"
                      title="Delete quiz"
                    >
                      <TrashIcon className="w-4 h-4" />
                    </button>
                  </div>
                  
                  <div className="space-y-3">
                    <div className="flex items-center justify-between text-sm">
                      <span className="text-white/60">Questions:</span>
                      <span className="text-white font-medium">{quiz.questions?.length || 0}</span>
                    </div>
                    <div className="flex items-center justify-between text-sm">
                      <span className="text-white/60">Time Limit:</span>
                      <span className="text-white font-medium">{quiz.timeLimit} min</span>
                    </div>
                    <div className="flex items-center justify-between text-sm">
                      <span className="text-white/60">Passing Score:</span>
                      <span className="text-white font-medium">{quiz.passingScore}%</span>
                    </div>
                    <div className="flex items-center justify-between text-sm">
                      <span className="text-white/60">Difficulty:</span>
                      <span className="text-white font-medium">{quiz.difficulty}</span>
                    </div>
                    <div className="flex items-center justify-between text-sm">
                      <span className="text-white/60">Status:</span>
                      <span className={`inline-flex items-center px-2 py-1 rounded-full text-xs font-medium ${
                        quiz.isActive 
                          ? 'bg-green-100 text-green-800 dark:bg-green-900 dark:text-green-200'
                          : 'bg-red-100 text-red-800 dark:bg-red-900 dark:text-red-200'
                      }`}>
                        {quiz.isActive ? (
                          <>
                            <CheckCircleIcon className="w-3 h-3 mr-1" />
                            Active
                          </>
                        ) : (
                          <>
                            <XCircleIcon className="w-3 h-3 mr-1" />
                            Inactive
                          </>
                        )}
                      </span>
                    </div>
                  </div>
                  
                  <div className="mt-4 flex items-center space-x-2">
                    <span className="text-xs text-white/60">Tags:</span>
                    {quiz.tags?.slice(0, 2).map((tag, index) => (
                      <span key={index} className="px-2 py-1 bg-white/20 text-white/80 rounded-full text-xs">
                        {tag}
                      </span>
                    ))}
                  </div>
                </div>
              ))}
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
