import { useState, useEffect, useCallback } from 'react';
import { useNavigate, useLocation } from 'react-router-dom';
import { useTheme } from '../hooks/useTheme';
import { useAuth } from '../context/AuthContextConstants';
import { useUserStats } from '../hooks/useUserStats';
import logger from '../utils/prettyLogger.js';
import Sidebar from '../components/Sidebar';
import TopBarUserAvatar from '../components/TopBarUserAvatar';
import SignRecognition from '../components/SignRecognition';
import {
  BoltIcon,
  FireIcon,
  SparklesIcon,
  StarIcon,
  ClockIcon,
  TrophyIcon,
  HandRaisedIcon,
  AcademicCapIcon,
  ExclamationTriangleIcon,
  CheckCircleIcon,
  ArrowRightIcon,
  PlayIcon,
  PuzzlePieceIcon,
  LockClosedIcon
} from '@heroicons/react/24/outline';

<<<<<<< HEAD
const API_BASE_URL = `${import.meta.env.VITE_API_BASE_URL || 'http://localhost:5000'}/api`;
=======
  const API_BASE_URL = `${import.meta.env.VITE_API_BASE_URL || 'http://localhost:5000'}/api`;
>>>>>>> dc62a1aeab24bf46cb3b9305bc8d4f9124e3d6d1

export default function Practice() {
  const { darkMode } = useTheme();
  const { logout } = useAuth();
  const { stats: userStats, refreshUserStats } = useUserStats();
  const navigate = useNavigate();
  const location = useLocation();

  // Practice state - Duolingo Style
  const [practiceMode, setPracticeMode] = useState('review');
  const [recentSigns, setRecentSigns] = useState([]);
  const [weakSigns, setWeakSigns] = useState([]);
  const [recentLimit, setRecentLimit] = useState(6);
  const [weakLimit, setWeakLimit] = useState(6);
  const [dailyGoal, setDailyGoal] = useState({ completed: 0, target: 5 });
  const [loading, setLoading] = useState(true);

  // Practice session state
  const [isPracticeSession, setIsPracticeSession] = useState(false);
  const [currentSign, setCurrentSign] = useState(null);
  const [sessionMode, setSessionMode] = useState('review');
  const [exerciseType, setExerciseType] = useState('sign-recognition');

  // Quiz requirements state
  const [quizRequirements, setQuizRequirements] = useState([]);

  // Theme variables - Match Learn and Quiz pages exactly
  const bg = darkMode ? 'bg-[#1A1A1A]' : 'bg-white';
  const text = darkMode ? 'text-white' : 'text-[#23272F]';
  const border = darkMode ? 'border-gray-600' : 'border-gray-300';
  const cardBg = darkMode ? 'bg-[#23272F]' : 'bg-gray-50';
  const statusBarBg = darkMode ? 'bg-[#1A1A1A]' : 'bg-gray-100';
  const textSecondary = darkMode ? 'text-gray-300' : 'text-gray-600';

  // Fetch quiz requirements for level progression
  const fetchQuizRequirements = async (token) => {
    try {
      // Get available quizzes
      const quizzesRes = await fetch(`${API_BASE_URL}/quiz`, {
        headers: token ? { 'Authorization': `Bearer ${token}` } : undefined
      });

      if (quizzesRes.ok) {
        const quizzesData = await quizzesRes.json();
        const autoGeneratedQuizzes = quizzesData.data?.filter(quiz =>
          quiz.tags?.includes('auto-generated') && quiz.isActive
        ) || [];
        // setAvailableQuizzes(autoGeneratedQuizzes);

        // Create quiz requirements based on available quizzes
        const requirements = autoGeneratedQuizzes.map(quiz => {
          const level = quiz.title.match(/Level (\d+)/)?.[1];
          return {
            level: parseInt(level) || 0,
            quiz: quiz,
            isAvailable: true,
            isPassed: quiz.userStatus?.passed || false
          };
        });

        setQuizRequirements(requirements);
      }
    } catch (error) {
      logger.errorWithStack('Error fetching quiz requirements', error, 'PRACTICE');
    }
  };

  const fetchPracticeData = useCallback(async () => {
    try {
      setLoading(true);
      const token = localStorage.getItem('token');

      // Fetch quiz requirements
      await fetchQuizRequirements(token);

      // recent attempts
      const recentRes = await fetch(`${API_BASE_URL}/practice/attempts/recent`, {
        headers: token ? { 'Authorization': `Bearer ${token}` } : undefined
      });
      const recentData = await recentRes.json().catch(() => ({}));
      const attempts = recentData.data || [];
      const recents = attempts.map(a => ({
        id: a.sign?._id || a.sign || a._id,
        word: a.expectedWord || a.sign?.word || 'Unknown Sign',
        accuracy: a.score || a.confidence || 0,
        lastPracticed: a.createdAt,
        category: a.sign?.category || 'practice'
      }));
      setRecentSigns(recents);
      // weak signs from attempts with low accuracy
      const weak = recents.filter(r => r.accuracy < 60).slice(0, 6);
      setWeakSigns(weak);
      // Get daily goal from user stats
      const userResponse = await fetch(`${API_BASE_URL}/api/auth/me`, {
        headers: token ? { 'Authorization': `Bearer ${token}` } : undefined
      });
      const userData = await userResponse.json().catch(() => ({}));
      const userStats = userData.user?.learningStats || {};

      // Calculate today's progress from practice attempts
      const today = new Date();
      today.setHours(0, 0, 0, 0);
      const todayAttempts = attempts.filter(attempt => {
        const attemptDate = new Date(attempt.lastPracticed || attempt.createdAt);
        attemptDate.setHours(0, 0, 0, 0);
        return attemptDate.getTime() === today.getTime();
      });

      const dailyGoalTarget = userStats.dailyGoal || 100;
      const dailyGoalCompleted = Math.min(todayAttempts.length * 20, dailyGoalTarget); // 20 XP per practice

      setDailyGoal({
        completed: dailyGoalCompleted,
        target: dailyGoalTarget
      });

    } catch (error) {
      logger.errorWithStack('Error fetching practice data', error, 'PRACTICE');
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    fetchPracticeData();
  }, [fetchPracticeData]);

  useEffect(() => {
    // Start session if navigated from dictionary with a specific sign
    (async () => {
      const state = location.state;
      if (state?.startPractice) {
        setIsPracticeSession(true);
        let signData = state.signData;
        if (!signData && state.specificSign) {
          try {
            // Try fetch by ID from DB list and match
            const res = await fetch(`${API_BASE_URL}/dictionary/db/signs?limit=500`);
            const data = await res.json().catch(() => ({}));
            const all = data.signs || [];
            signData = all.find(s => (s._id || s.id) === state.specificSign) || { word: 'Sign', id: state.specificSign };
          } catch {
            signData = { word: 'Sign', id: state.specificSign };
          }
        }
        setCurrentSign(signData || { word: 'Sign' });
        setSessionMode(state.mode || 'review');
        setExerciseType(state.exerciseType || 'sign-recognition');
      }
    })();
  }, [location.state]);

  const handleLogout = () => {
    logout();
    navigate('/');
  };

  const startPractice = (sign, mode = 'review', exerciseType = 'sign-recognition') => {
    // Start practice session
    setIsPracticeSession(true);
    setCurrentSign(sign);
    setSessionMode(mode);
    setExerciseType(exerciseType);
  };

  const endPracticeSession = () => {
    setIsPracticeSession(false);
    setCurrentSign(null);
    setSessionMode('review');
    setExerciseType('sign-recognition');
  };

  const handleRecognitionResult = useCallback(async (result) => {
    logger.recognition('Recognition result received', result, 'PRACTICE');

    // Only save if it's a valid, correct recognition or high confidence
    if (result.isCorrect || (result.isValid && result.confidence > 0.8)) {
      try {
        const token = localStorage.getItem('token');
        if (!token) return;

        await fetch(`${API_BASE_URL}/practice/attempt`, {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            'Authorization': `Bearer ${token}`
          },
          body: JSON.stringify({
            signId: currentSign.id || currentSign._id,
            word: currentSign.word,
            correct: true,
            confidence: result.confidence,
            mode: 'webcam-geometric'
          })
        });

        // Refresh global user stats (XP, Streak, Level)
        refreshUserStats();

        // Log success
        logger.debug('Practice attempt saved successfully', null, 'PRACTICE');

        // Update local daily goal visually for immediate feedback
        setDailyGoal(prev => ({
          ...prev,
          completed: Math.min(prev.completed + 20, prev.target)
        }));

      } catch (error) {
        logger.error('Failed to save practice attempt', error);
      }
    }
  }, [currentSign]);

  const renderExerciseContent = () => {
    switch (exerciseType) {
      case 'sign-recognition':
        return (
          <SignRecognition
            targetSign={currentSign}
            onRecognition={handleRecognitionResult}
            mode="webcam"
          />
        );

      case 'flashcard':
        return (
          <div className="text-center space-y-6">
            {/* Show cover image or first variant */}
            <div className="w-64 h-48 bg-white/10 backdrop-blur-md border border-white/20 rounded-lg mx-auto overflow-hidden">
              {currentSign.coverImage ? (
                <img
                  src={currentSign.coverImage}
                  alt={`Sign for ${currentSign.word}`}
                  className="w-full h-full object-cover"
                />
              ) : currentSign.variants && currentSign.variants.length > 0 ? (
                currentSign.variants[0].type === 'image' ? (
                  <img
                    src={currentSign.variants[0].path}
                    alt={`Sign for ${currentSign.word}`}
                    className="w-full h-full object-cover"
                  />
                ) : (
                  <video
                    src={currentSign.variants[0].path}
                    className="w-full h-full object-cover"
                    autoPlay
                    loop
                    muted
                  />
                )
              ) : (
                <div className="w-full h-full flex items-center justify-center">
                  <span className="text-white/50">Sign Demonstration</span>
                </div>
              )}
            </div>
            <div>
              <h3 className="text-2xl font-bold mb-2">{currentSign.word}</h3>
              <p className="text-white/70 mb-4">
                Study this sign and its meaning
              </p>
              {currentSign.variants && currentSign.variants.length > 1 && (
                <p className="text-sm text-blue-600 mb-4">
                  This sign has {currentSign.variants.length} learning variants
                </p>
              )}
              <button
                onClick={() => handleRecognitionResult({ isValid: true, confidence: 0.9 })}
                className="px-6 py-3 bg-green-500 text-white rounded-lg hover:bg-green-600 transition-colors"
              >
                I understand this sign
              </button>
            </div>
          </div>
        );

      case 'video-tutorial':
        return (
          <div className="text-center space-y-6">
            <div className="w-full max-w-md mx-auto">
              <div className="relative bg-black rounded-lg overflow-hidden">
                {currentSign.variants && currentSign.variants.find(v => v.type === 'video') ? (
                  <video
                    src={currentSign.variants.find(v => v.type === 'video').path}
                    className="w-full h-48 object-cover"
                    controls
                    autoPlay
                  />
                ) : (
                  <div className="w-full h-48 bg-gray-800 flex items-center justify-center">
                    <PlayIcon className="w-16 h-16 text-white" />
                  </div>
                )}
                <div className="absolute bottom-4 left-4 right-4">
                  <div className="bg-black bg-opacity-50 rounded p-2">
                    <div className="text-white text-sm font-medium">{currentSign.word}</div>
                  </div>
                </div>
              </div>
            </div>
            <div>
              <h3 className="text-xl font-bold mb-2">{currentSign.word}</h3>
              <p className="text-white/70 mb-4">
                Watch the video tutorial to learn this sign
              </p>
              {currentSign.variants && currentSign.variants.length > 1 && (
                <p className="text-sm text-blue-600 mb-4">
                  This sign has {currentSign.variants.length} learning variants
                </p>
              )}
              <div className="flex space-x-4 justify-center">
                <button
                  onClick={() => handleRecognitionResult({ isValid: true, confidence: 0.9 })}
                  className="px-6 py-3 bg-green-500 text-white rounded-lg hover:bg-green-600 transition-colors"
                >
                  I learned this sign
                </button>
                <button
                  onClick={() => handleRecognitionResult({ isValid: false, confidence: 0.3 })}
                  className="px-6 py-3 bg-gray-500 text-white rounded-lg hover:bg-gray-600 transition-colors"
                >
                  Need more practice
                </button>
              </div>
            </div>
          </div>
        );

      default:
        return (
          <SignRecognition
            targetSign={currentSign}
            onRecognition={handleRecognitionResult}
            mode="webcam"
          />
        );
    }
  };

  const getAccuracyColor = (accuracy) => {
    if (accuracy >= 80) return 'text-green-500';
    if (accuracy >= 60) return 'text-yellow-500';
    return 'text-red-500';
  };

  const getAccuracyBg = (accuracy) => {
    if (accuracy >= 80) return 'bg-green-500/20 border border-green-500/30';
    if (accuracy >= 60) return 'bg-yellow-500/20 border border-yellow-500/30';
    return 'bg-red-500/20 border border-red-500/30';
  };

  if (loading) {
    return (
      <div className={`min-h-screen ${bg} flex items-center justify-center`}>
        <div className="text-center">
          <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-500 mx-auto mb-4"></div>
          <p className={`text-lg ${text}`}>Loading practice data...</p>
        </div>
      </div>
    );
  }

  // Practice Session View
  if (isPracticeSession && currentSign) {
    return (
      <div className={`min-h-screen ${bg} ${text} overflow-x-hidden`}>
        {/* Top Status Bar */}
        <div className={`${statusBarBg} border-b ${border} px-6 py-3 pl-64 sticky top-0 z-30`}>
          <div className="flex items-center justify-between w-full">
            <div className="flex items-center space-x-4">
              <button
                onClick={endPracticeSession}
                className="flex items-center space-x-2 text-gray-400 hover:text-white transition-colors"
              >
                <span>←</span>
                <span>Back to Practice</span>
              </button>
            </div>

            <div className="flex items-center space-x-4">
              <div className="flex items-center space-x-2">
                <FireIcon className="w-5 h-5 text-orange-400" />
                <span className="font-semibold">{userStats.streak}</span>
              </div>
              <div className="flex items-center space-x-2">
                <SparklesIcon className="w-5 h-5 text-blue-400" />
                <span className="font-semibold">{userStats.totalXP} XP</span>
              </div>
              <div className="flex items-center space-x-2">
                <StarIcon className="w-5 h-5 text-yellow-400" />
                <span className="font-semibold">Rank {userStats.level}</span>
              </div>
              <TopBarUserAvatar size={8} />
            </div>
          </div>
        </div>

        <div className="flex">
          {/* Fixed Left Sidebar - Navigation */}
          <Sidebar handleLogout={handleLogout} />

          {/* Main Content Area */}
          <div className={`flex-1 ml-64 ${bg} overflow-hidden pt-16`}>
            <div className="max-w-7xl mx-auto min-h-0">
              <div className="flex min-h-0">
                {/* Main Content */}
                <div className="flex-1 p-6">
                  {/* Practice Session Header */}
                  <div className="mb-8">
                    <div className="flex items-center justify-between">
                      <div>
                        <h1 className={`text-3xl font-bold ${text} mb-2`}>Practice Session</h1>
                        <p className={`${textSecondary}`}>
                          Practice the sign for "{currentSign.word}"
                        </p>
                      </div>
                      <div className="flex items-center space-x-4">
                        <span className={`px-3 py-1 rounded-full text-sm font-medium ${sessionMode === 'review' ? 'bg-blue-100 text-blue-800' :
                          sessionMode === 'weak' ? 'bg-red-100 text-red-800' :
                            sessionMode === 'speed' ? 'bg-green-100 text-green-800' :
                              'bg-purple-100 text-purple-800'
                          }`}>
                          {sessionMode.charAt(0).toUpperCase() + sessionMode.slice(1)} Mode
                        </span>
                        <span className={`px-3 py-1 rounded-full text-sm font-medium ${exerciseType === 'sign-recognition' ? 'bg-blue-100 text-blue-800' :
                          exerciseType === 'flashcard' ? 'bg-green-100 text-green-800' :
                            exerciseType === 'video-tutorial' ? 'bg-purple-100 text-purple-800' :
                              'bg-gray-100 text-gray-800'
                          }`}>
                          {exerciseType === 'sign-recognition' ? '👁️ Recognition' :
                            exerciseType === 'flashcard' ? '📚 Flashcard' :
                              exerciseType === 'video-tutorial' ? '▶️ Tutorial' :
                                exerciseType}
                        </span>
                      </div>
                    </div>
                  </div>

                  {/* Sign Recognition Component */}
                  <div className={`${cardBg} rounded-lg border ${border} p-6`}>
                    <div className="text-center mb-6">
                      <h2 className={`text-2xl font-bold ${text} mb-2`}>
                        Practice: {currentSign.word}
                      </h2>
                      <p className={`${textSecondary}`}>
                        Show this sign to the camera
                      </p>
                    </div>

                    {renderExerciseContent()}
                  </div>
                </div>
              </div>
            </div>
          </div>

          {/* Subtle line between sidebar and content */}
          <div className="fixed left-64 top-0 h-screen w-px bg-gray-600 z-40"></div>
        </div>
      </div>
    );
  }

  return (
    <div className={`min-h-screen ${bg} ${text} overflow-x-hidden`}>
      {/* Fixed Top Status Bar - Match Learn and Quiz pages exactly */}
      <div className={`fixed top-0 left-0 right-0 z-50 ${statusBarBg} border-b ${border} px-6 py-3 pl-64`}>
        <div className="flex items-center justify-between w-full">
          <div className="flex items-center space-x-4">
            {/* Empty space on the left */}
          </div>

          <div className="flex items-center space-x-4">
            <div className="flex items-center space-x-2">
              <FireIcon className="w-5 h-5 text-orange-400" />
              <span className="font-semibold">{userStats.streak}</span>
            </div>
            <div className="flex items-center space-x-2">
              <SparklesIcon className="w-5 h-5 text-blue-400" />
              <span className="font-semibold">{userStats.totalXP} XP</span>
            </div>
            <div className="flex items-center space-x-2">
              <StarIcon className="w-5 h-5 text-yellow-400" />
              <span className="font-semibold">Lv {userStats.level}</span>
              <span className="text-sm text-gray-400">({userStats.xpToNextLevel} to next)</span>
            </div>
            <TopBarUserAvatar size={8} />
          </div>
        </div>
      </div>

      <div className="flex flex-1 overflow-hidden">
        {/* Fixed Left Sidebar - Navigation */}
        <Sidebar handleLogout={handleLogout} />

        {/* Subtle line between sidebar and content */}
        <div className="fixed left-64 top-0 h-screen w-px bg-gray-300 dark:bg-gray-600 z-40"></div>

        {/* Scrollable Main Content Area */}
        <div className={`flex-1 ml-64 ${bg} overflow-y-auto`}>
          <div className="p-6 pt-20">
            {/* Header - Duolingo Style */}
            <div className={`mb-8 p-6 rounded-2xl ${cardBg} border ${border}`}>
              <div className="flex items-center justify-between">
                <div>
                  <h1 className="text-3xl font-bold text-white mb-2">Practice</h1>
                  <p className="text-white/70">
                    Strengthen your sign language skills
                  </p>
                </div>
                <div className="flex items-center space-x-4">
                  <button
                    onClick={() => navigate('/learn')}
                    className="px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors"
                  >
                    <AcademicCapIcon className="w-4 h-4 inline mr-2" />
                    Learning Path
                  </button>
                  <button
                    onClick={() => navigate('/dictionary')}
                    className="px-4 py-2 bg-green-600 text-white rounded-lg hover:bg-green-700 transition-colors"
                  >
                    <HandRaisedIcon className="w-4 h-4 inline mr-2" />
                    Dictionary
                  </button>
                </div>
              </div>
            </div>

            {/* Daily Goal - Duolingo Style */}
            <div className={`${cardBg} rounded-2xl border ${border} p-6 mb-8`}>
              <div className="flex items-center justify-between mb-4">
                <h3 className="text-xl font-bold text-white">Today's Practice Goal</h3>
                <span className="text-sm text-white/60">
                  {dailyGoal.completed} / {dailyGoal.target} signs practiced
                </span>
              </div>
              <div className="w-full bg-white/20 rounded-full h-3 mb-4">
                <div
                  className="bg-blue-500 h-3 rounded-full transition-all duration-500"
                  style={{ width: `${(dailyGoal.completed / dailyGoal.target) * 100}%` }}
                ></div>
              </div>
              <div className="flex items-center justify-between text-sm">
                <span className="text-white/60">Keep practicing to maintain your streak!</span>
                <span className="text-blue-400 font-semibold">
                  {userStats.streak} day streak
                </span>
              </div>
            </div>

            {/* Practice Modes */}
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-8 mb-8">
              {/* Recent Signs */}
              <div className={`${cardBg} rounded-2xl border ${border} p-6 `}>
                <div className="flex items-center justify-between mb-4">
                  <h3 className="text-xl font-bold text-white">Recent Signs</h3>
                  <div className="flex items-center space-x-3">
                    <span className="text-sm text-white/60">Practice what you learned</span>
                    {recentSigns.length > recentLimit && (
                      <button
                        onClick={() => setRecentLimit(prev => prev + 6)}
                        className="text-blue-400 text-sm hover:underline"
                      >
                        Show more
                      </button>
                    )}
                    {recentLimit > 6 && (
                      <button
                        onClick={() => setRecentLimit(6)}
                        className="text-white/60 text-sm hover:underline"
                      >
                        Collapse
                      </button>
                    )}
                  </div>
                </div>

                <div className="space-y-3 max-h-72 overflow-y-auto pr-1">
                  {recentSigns.length === 0 ? (
                    <div className="text-center py-8">
                      <div className="w-16 h-16 mx-auto mb-4 bg-white/10 rounded-full flex items-center justify-center">
                        <ClockIcon className="w-8 h-8 text-white/50" />
                      </div>
                      <p className="text-white/60 mb-2">No recent practice attempts</p>
                      <p className="text-sm text-white/40">Start practicing signs to see them here</p>
                    </div>
                  ) : (
                    recentSigns.slice(0, recentLimit).map((sign) => (
                      <div
                        key={sign.id}
                        className={`flex items-center justify-between p-3 ${cardBg} rounded-2xl border ${border}`}
                      >
                        <div className="flex items-center space-x-3">
                          <div className={`p-2 rounded-lg ${getAccuracyBg(sign.accuracy)}`}>
                            <CheckCircleIcon className={`w-5 h-5 ${getAccuracyColor(sign.accuracy)}`} />
                          </div>
                          <div>
                            <h4 className="font-semibold text-white">{sign.word}</h4>
                            <p className="text-sm text-white/60">{sign.category}</p>
                          </div>
                        </div>
                        <div className="flex items-center space-x-3">
                          <span className={`text-sm font-semibold ${getAccuracyColor(sign.accuracy)}`}>
                            {sign.accuracy}%
                          </span>
                          <div className="flex space-x-1">
                            <button
                              onClick={() => startPractice(sign, 'review', 'sign-recognition')}
                              className="px-3 py-1 bg-blue-500 text-white rounded text-sm hover:bg-blue-600 transition-colors"
                              title="Practice Recognition"
                            >
                              Practice
                            </button>
                          </div>
                        </div>
                      </div>
                    ))
                  )}
                </div>
              </div>

              {/* Weak Areas */}
              <div className={`${cardBg} rounded-2xl border ${border} p-6 `}>
                <div className="flex items-center justify-between mb-4">
                  <h3 className="text-xl font-bold text-white">Weak Areas</h3>
                  <div className="flex items-center space-x-3">
                    <span className="text-sm text-white/60">Focus on improvement</span>
                    {weakSigns.length > weakLimit && (
                      <button
                        onClick={() => setWeakLimit(prev => prev + 6)}
                        className="text-blue-400 text-sm hover:underline"
                      >
                        Show more
                      </button>
                    )}
                    {weakLimit > 6 && (
                      <button
                        onClick={() => setWeakLimit(6)}
                        className="text-white/60 text-sm hover:underline"
                      >
                        Collapse
                      </button>
                    )}
                  </div>
                </div>

                <div className="space-y-3 max-h-72 overflow-y-auto pr-1">
                  {weakSigns.length === 0 ? (
                    <div className="text-center py-8">
                      <div className="w-16 h-16 mx-auto mb-4 bg-white/10 rounded-full flex items-center justify-center">
                        <ExclamationTriangleIcon className="w-8 h-8 text-white/50" />
                      </div>
                      <p className="text-white/60 mb-2">No weak areas identified</p>
                      <p className="text-sm text-white/40">Great job! Keep practicing to maintain your skills</p>
                    </div>
                  ) : (
                    weakSigns.slice(0, weakLimit).map((sign) => (
                      <div
                        key={sign.id}
                        className={`flex items-center justify-between p-3 ${cardBg} rounded-2xl border ${border}`}
                      >
                        <div className="flex items-center space-x-3">
                          <div className={`p-2 rounded-lg ${getAccuracyBg(sign.accuracy)}`}>
                            <ExclamationTriangleIcon className={`w-5 h-5 ${getAccuracyColor(sign.accuracy)}`} />
                          </div>
                          <div>
                            <h4 className="font-semibold text-white">{sign.word}</h4>
                            <p className="text-sm text-white/60">{sign.category}</p>
                          </div>
                        </div>
                        <div className="flex items-center space-x-3">
                          <span className={`text-sm font-semibold ${getAccuracyColor(sign.accuracy)}`}>
                            {sign.accuracy}%
                          </span>
                          <div className="flex space-x-1">
                            <button
                              onClick={() => startPractice(sign, 'weak', 'sign-recognition')}
                              className="px-3 py-1 bg-red-500 text-white rounded text-sm hover:bg-red-600 transition-colors"
                              title="Practice Recognition"
                            >
                              Practice
                            </button>
                          </div>
                        </div>
                      </div>
                    ))
                  )}
                </div>
              </div>

              {/* Quiz Requirements for Level Progression */}
              {quizRequirements.length > 0 && (
                <div className={`${cardBg} rounded-2xl border ${border} p-6  mb-8`}>
                  <div className="flex items-center justify-between mb-4">
                    <h3 className="text-xl font-bold text-white">Level Progression</h3>
                    <div className="flex items-center space-x-2">
                      <PuzzlePieceIcon className="w-5 h-5 text-purple-400" />
                      <span className="text-sm text-white/60">Pass quizzes to unlock next levels</span>
                    </div>
                  </div>

                  <div className="space-y-4">
                    {quizRequirements.map((requirement, index) => (
                      <div key={index} className={`p-4 ${cardBg} rounded-2xl border ${border}`}>
                        <div className="flex items-center justify-between">
                          <div className="flex items-center space-x-4">
                            <div className="p-3 bg-purple-500 rounded-full">
                              <PuzzlePieceIcon className="w-6 h-6 text-white" />
                            </div>
                            <div>
                              <h4 className="text-lg font-semibold text-white">
                                {requirement.quiz.title}
                              </h4>
                              <p className="text-white/70 text-sm">
                                {requirement.quiz.description}
                              </p>
                              <div className="flex items-center space-x-4 mt-2 text-sm">
                                <span className="text-white/60">
                                  {requirement.quiz.questions?.length || 0} questions
                                </span>
                                <span className="text-white/60">
                                  {requirement.quiz.timeLimit} min
                                </span>
                                <span className="text-white/60">
                                  Pass: {requirement.quiz.passingScore}%
                                </span>
                              </div>
                            </div>
                          </div>

                          <div className="flex items-center space-x-3">
                            {requirement.isPassed ? (
                              <div className="flex items-center space-x-2 text-green-400">
                                <CheckCircleIcon className="w-5 h-5" />
                                <span className="text-sm font-medium">Passed</span>
                              </div>
                            ) : (
                              <div className="flex items-center space-x-2">
                                <LockClosedIcon className="w-5 h-5 text-white/60" />
                                <button
                                  onClick={() => navigate(`/quiz/${requirement.quiz._id}`)}
                                  className="px-4 py-2 bg-purple-500 text-white rounded-lg hover:bg-purple-600 transition-colors text-sm"
                                >
                                  Take Quiz
                                </button>
                              </div>
                            )}
                          </div>
                        </div>
                      </div>
                    ))}
                  </div>
                </div>
              )}

              {/* Practice Options */}
              <div className={`${cardBg} rounded-lg border ${border} p-6`}>
                <h3 className={`text-xl font-bold ${text} mb-4`}>Practice Options</h3>
                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
                  <button
                    onClick={() => setPracticeMode('review')}
                    className={`p-4 rounded-lg border transition-all ${practiceMode === 'review'
                      ? 'border-blue-500 bg-blue-500/20'
                      : 'border-white/20 hover:border-blue-300'
                      }`}
                  >
                    <div className="flex items-center space-x-3">
                      <ClockIcon className="w-6 h-6 text-blue-500" />
                      <div className="text-left">
                        <h4 className="font-semibold">Review Practice</h4>
                        <p className="text-sm text-white/50">Practice recent signs</p>
                      </div>
                    </div>
                  </button>

                  <button
                    onClick={() => setPracticeMode('weak')}
                    className={`p-4 rounded-lg border transition-all ${practiceMode === 'weak'
                      ? 'border-orange-500 bg-orange-500/20'
                      : 'border-white/20 hover:border-orange-300'
                      }`}
                  >
                    <div className="flex items-center space-x-3">
                      <ExclamationTriangleIcon className="w-6 h-6 text-orange-500" />
                      <div className="text-left">
                        <h4 className="font-semibold">Weak Areas</h4>
                        <p className="text-sm text-white/50">Focus on improvement</p>
                      </div>
                    </div>
                  </button>

                  <button
                    onClick={() => {
                      setIsPracticeSession(true);
                      setCurrentSign({ word: 'Free Practice', id: 'free-practice' });
                      setSessionMode('free');
                      setExerciseType('sign-recognition');
                    }}
                    className={`p-4 rounded-lg border transition-all ${practiceMode === 'free'
                      ? 'border-green-500 bg-green-500/20'
                      : 'border-white/20 hover:border-green-300'
                      }`}
                  >
                    <div className="flex items-center space-x-3">
                      <PlayIcon className="w-6 h-6 text-green-500" />
                      <div className="text-left">
                        <h4 className="font-semibold">Free Practice</h4>
                        <p className="text-sm text-white/50">Practice any sign</p>
                      </div>
                    </div>
                  </button>
                </div>
              </div>

              {/* Quick Actions */}
              <div className={`${cardBg} rounded-lg border ${border} p-6 mt-8`}>
                <h3 className={`text-xl font-bold ${text} mb-4`}>Quick Actions</h3>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <button
                    onClick={() => navigate('/dictionary')}
                    className="flex items-center space-x-3 p-4 bg-blue-600 hover:bg-blue-700 text-white rounded-lg transition-colors"
                  >
                    <HandRaisedIcon className="w-6 h-6" />
                    <span>Browse Dictionary</span>
                  </button>
                  <button
                    onClick={() => navigate('/quiz')}
                    className="flex items-center space-x-3 p-4 bg-purple-600 hover:bg-purple-700 text-white rounded-lg transition-colors"
                  >
                    <PlayIcon className="w-6 h-6" />
                    <span>Take a Quiz</span>
                  </button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}